name: "Metriker Ingest"
description: "Send SBOM and coverage metrics to Metriker."
author: "metriker"
inputs:
  api_key:
    description: "API key for Metriker (use secrets)"
    required: true
  component:
    description: "Metric component tag sent as x-metric-component"
    required: false
  sbom_path:
    description: "Path to the SBOM JSON file"
    required: false
    default: ""
  coverage_path:
    description: "Path to the LCOV file"
    required: false
    default: ""
  metric_name:
    description: "Custom metric name to ingest"
    required: false
    default: ""
  metric_value:
    description: "Custom metric numeric value to ingest"
    required: false
    default: ""
  fail_on_error:
    description: "Fail the action if ingestion fails"
    required: false
    default: "true"
runs:
  using: "composite"
  steps:
    - name: Ingest SBOM to Metriker
      if: inputs.sbom_path != ''
      shell: bash
      run: |
        api_base="https://metriker.com"
        repo_slug="${{ github.repository }}"
        component="${{ inputs.component }}"
        git_branch="${{ github.ref_name }}"
        git_commit="${{ github.sha }}"
        sbom_path="${{ inputs.sbom_path }}"
        response_file="$(mktemp)"
        http_code=$(curl -sS -o "$response_file" -w "%{http_code}" -X POST \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ inputs.api_key }}" \
          -H "x-metric-component: ${component}" \
          -H "x-git-branch: ${git_branch}" \
          -H "x-git-commit: ${git_commit}" \
          -d "@${sbom_path}" \
          "${api_base}/api/ingest/${repo_slug}/sbom")
        curl_exit=$?
        if [[ $curl_exit -ne 0 ]]; then
          echo "SBOM ingestion failed (curl exit ${curl_exit})."
          cat "$response_file" || true
          if [[ "${{ inputs.fail_on_error }}" == 'true' ]]; then
            exit 1
          fi
        elif [[ "$http_code" -ge 200 && "$http_code" -lt 300 ]]; then
          echo "SBOM ingested successfully."
        else
          echo "SBOM ingestion failed (HTTP ${http_code})."
          cat "$response_file" || true
          if [[ "${{ inputs.fail_on_error }}" == 'true' ]]; then
            exit 1
          fi
        fi

    - name: Ingest coverage to Metriker
      if: inputs.coverage_path != ''
      shell: bash
      run: |
        api_base="https://metriker.com"
        repo_slug="${{ github.repository }}"
        component="${{ inputs.component }}"
        git_branch="${{ github.ref_name }}"
        git_commit="${{ github.sha }}"
        coverage_path="${{ inputs.coverage_path }}"
        response_file="$(mktemp)"
        http_code=$(curl -sS -o "$response_file" -w "%{http_code}" -X POST \
          -H "Content-Type: text/plain" \
          -H "Authorization: Bearer ${{ inputs.api_key }}" \
          -H "x-metric-component: ${component}" \
          -H "x-git-branch: ${git_branch}" \
          -H "x-git-commit: ${git_commit}" \
          --data-binary "@${coverage_path}" \
          "${api_base}/api/ingest/${repo_slug}/coverage")
        curl_exit=$?
        if [[ $curl_exit -ne 0 ]]; then
          echo "Coverage ingestion failed (curl exit ${curl_exit})."
          cat "$response_file" || true
          if [[ "${{ inputs.fail_on_error }}" == 'true' ]]; then
            exit 1
          fi
        elif [[ "$http_code" -ge 200 && "$http_code" -lt 300 ]]; then
          echo "Coverage ingested successfully."
        else
          echo "Coverage ingestion failed (HTTP ${http_code})."
          cat "$response_file" || true
          if [[ "${{ inputs.fail_on_error }}" == 'true' ]]; then
            exit 1
          fi
        fi

    - name: Ingest custom metric to Metriker
      if: inputs.metric_name != '' && inputs.metric_value != ''
      shell: bash
      run: |
        api_base="https://metriker.com"
        repo_slug="${{ github.repository }}"
        component="${{ inputs.component }}"
        git_branch="${{ github.ref_name }}"
        git_commit="${{ github.sha }}"
        metric_name="${{ inputs.metric_name }}"
        metric_value="${{ inputs.metric_value }}"
        response_file="$(mktemp)"
        json_body=$(printf '{"value": %s}' "$metric_value")
        http_code=$(curl -sS -o "$response_file" -w "%{http_code}" -X POST \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ inputs.api_key }}" \
          -H "x-metric-component: ${component}" \
          -H "x-git-branch: ${git_branch}" \
          -H "x-git-commit: ${git_commit}" \
          -d "$json_body" \
          "${api_base}/api/ingest/${repo_slug}/metrics/${metric_name}")
        curl_exit=$?
        if [[ $curl_exit -ne 0 ]]; then
          echo "Custom metric ingestion failed (curl exit ${curl_exit})."
          cat "$response_file" || true
          if [[ "${{ inputs.fail_on_error }}" == 'true' ]]; then
            exit 1
          fi
        elif [[ "$http_code" -ge 200 && "$http_code" -lt 300 ]]; then
          echo "Custom metric ingested successfully."
        else
          echo "Custom metric ingestion failed (HTTP ${http_code})."
          cat "$response_file" || true
          if [[ "${{ inputs.fail_on_error }}" == 'true' ]]; then
            exit 1
          fi
        fi
